### ISSUE TITLE
AWS IoT SiteWise config

### ISSUE THREAD

**Issue by vikram291194** [awsdocs/aws-iot-sitewise-user-guide#3]
How do i config my jetson nano running linux ubuntu 18.04 for AWS Site Wise? I have already installed the greengrass core and also SDK and verified that the lambda function operation by subscribing to the hello/world topic and seeing the MQTT messages on the test client.
I am using Stream manager and hence i would ike to know how to config the SDK core for IoTSiteWise and also the BatchPutassetPropertyValue config.
Kindly provide me with the above info..

**Comment by feiyxAWS** [comment]
For more information about how to set up your device, see [Ingesting data using a gateway](https://docs.aws.amazon.com/iot-sitewise/latest/userguide/gateways.html), in the AWS IoT SiteWise User Guide. Thanks!

**Comment by feiyxAWS** [comment]
> How do i config my jetson nano running linux ubuntu 18.04 for AWS Site Wise? I have already installed the greengrass core and also SDK and verified that the lambda function operation by subscribing to the hello/world topic and seeing the MQTT messages on the test client.
> I am using Stream manager and hence i would ike to know how to config the SDK core for IoTSiteWise and also the BatchPutassetPropertyValue config.
> Kindly provide me with the above info..

For more information about how to set up your device, see [Ingesting data using a gateway](https://docs.aws.amazon.com/iot-sitewise/latest/userguide/gateways.html) in the AWS IoT SiteWise User Guide. Thanks!

**Comment by vikram291194** [comment]
Hi
I have gone through those docs but as i said above there's no exact config file or an example to show how to ingest data to SiteWise using lambda functions

**Comment by feiyxAWS** [comment]
Hello, 

You can ingest data to SiteWise by using [SiteWise gateways](https://docs.aws.amazon.com/iot-sitewise/latest/userguide/gateways-ggv2.html) or [Greengrass stream manager](https://docs.aws.amazon.com/greengrass/v2/developerguide/manage-data-streams.html). 

You can run Lambda functions on Greengrass core devices. For more information, see [Run AWS Lambda functions](https://docs.aws.amazon.com/greengrass/v2/developerguide/run-lambda-functions.html) in the AWS Greengrass V2 Developer Guide. 

If you have further feedback on our documentation, please visit our [documentation site](https://docs.aws.amazon.com/iot-sitewise/latest/userguide/what-is-sitewise.html). You can use the *Feedback* button in the upper-right corner.  

Thanks!
