### ISSUE TITLE
doc_source/monitor-cloudwatch-metrics.md is not up to date

### ISSUE THREAD

**Issue by ArneDeTemmerman** [awsdocs/aws-iot-sitewise-user-guide#4]
These metrics are not mentioned in the documentation:

IoTSiteWisePublisher.PublishRejectedCount
IoTSiteWisePublisher.PublisherPrimaryCheckpoint
IoTSiteWisePublisher.PublisherMessagesRemaining
OpcUaCollector.ConversionErrors

**Comment by feiyxAWS** [comment]
Hello. 

Thanks for your feedback! We will add these metrics to the documentation.
